name: rabahdj_local_app
description: "Local Wi-Fi Social Media App by RabahDj"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http: ^1.2.0
  shared_preferences: ^2.2.0 # مكتبة التخزي

flutter:
  uses-material-design: true
