      # 🟢 خطوة الـ Bundle الرسمية والمضمونة لمشاريع Expo
      - name: 📦 Bundle Assets & Latest JS Code
        run: |
          mkdir -p android/app/src/main/assets
          npx expo export:embed --platform android --dev false --asset-catalog-dest android/app/src/main/res
